language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-6
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
    - os: osx
      osx_image: xcode9.4
      compiler:
        - clang
      env: COMPILER_NAME=clang CXX=clang++ CC=clang

script:
  - cmake .
  - cmake --build .