language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-6
    - os: osx
      osx_image: xcode9.4
      compiler:
        - clang

script:
  - cmake .
  - cmake --build .