language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
           - g++-6
      env:
        - MATRIX_EVAL="CXX=g++-6 && CC=gcc-6"
    - os: osx
      osx_image: xcode9.4
      env: 
        - MATRIX_EVAL="CXX=clang++ && CC=clang"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake .
  - cmake --build .
